version: "3.9"

services:
  dvc_example:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: dvc_example:aavasenkov
    container_name: dvc_example_aavasenkov
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "cd / && sleep infinity"
